os:
  - linx
  - osx

language: c
sudo: required

env:
  matrix:
    - CONDA_PY=27
    - CONDA_PY=33
    - CONDA_PY=34
    - CONDA_PY=35

addons:
  apt:
    packages:
    - gcc
    - g++

script:
  - ./run_tests_travis.sh

notifications:
  email:
    - andreas.heger@gmail.com
